development:
  adapter: postgresql
  database: rsig
  host: localhost
  username: postgres
  password: vectra

test:
  adapter: postgresql
  database: rsig_test
  host: localhost
  username: postgres
  password: vectra

production:
  adapter: postgresql
  database: rsig_production
  host: localhost
  username: postgres
  password: vectra
