development:
  adapter: postgresql
  database: rsig_development
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: rsig_test
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: rsig_production
  host: localhost
  username: postgres
  password: postgres.gitignore
